version: '3'

services:
  app:
    image: sample_flask_app
    build: .
    env_file:
      - 'dev.env'
    environment:
      HOST_HOSTNAME: ${hostname}

  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file:
      - 'dev.env'

  adminer:
    # DB management. Visit localhost:8080, connect to 'mysql' as 'root'
    image: adminer
    restart: always
    ports:
      - 8080:8080
