version: '3'

services:
  server:
    image: sample_flask_server
    build: .

  nats:
    image: nats:2-alpine

  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root

  adminer:
    # DB management. Visit localhost:8080, connect to 'mysql' as 'root'
    image: adminer
    restart: always
    ports:
      - 8080:8080
